repos:
  - repo: https://github.com/jeffmay/pre-commit-hooks-scala
    rev: v0.0.1
    hooks:
      - id: scalafmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
